---
os: linux
arch:
 - amd64
 - ppc64le

language: c
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get install -y pkg-config
script:
  - ./autogen.sh
  - make
  - make clean
  - sudo apt-get install -y libconfig-dev || sudo apt-get install -y libconfig8-dev
  - ./autogen.sh
  - make
